import{a as kq,b as Uq,c as u}from"./birdie_terminal-ym7aeztf.js";import{$ as Yq,C as v,D as zq,Ea as Eq,Fa as fq,I as w,N as V,O,P as Jq,R as Nq,S as Qq,W as Vq,X as Xq,ba as Zq,ca as xq,da as G,e as X,ea as T,f as H,fa as R,g as q,ga as _,h as i,ja as j,k as o,ka as Hq,la as L,ma as Q,na as Iq,oa as Y,p as s,qa as Dq,s as e,sa as F,t,ta as Z,xa as Kq,y as qq,ya as Sq,za as bq}from"./birdie_terminal-bn2yg0n6.js";var Aq="src/blog/interactive/birdie_terminal.gleam";class f extends X{constructor(z,N,J,x){super();this.state=z,this.command=N,this.steps=J,this.tests_timing=x}}class y extends X{constructor(z){super();this[0]=z}}class S extends X{constructor(z){super();this[0]=z}}class W extends X{}class K extends X{}class B extends X{}class E extends X{}class M extends X{}class D extends X{}class P extends X{}class r extends X{}class g extends X{constructor(z){super();this.command=z}}class p extends X{constructor(z){super();this[0]=z}}class l extends X{constructor(z,N){super();this.elapsed=z,this.success=N}}class hq extends X{constructor(z,N){super();this.elapsed=z,this.success=N}}class b extends X{}class k extends X{}class U extends X{}class h extends X{}class Bq extends X{constructor(z){super();this.value=z}}function Wq(z){if(z instanceof K)return"compiling...";else if(z instanceof B)return"running tests...";else if(z instanceof E)return"try `gleam test`...";else if(z instanceof M)return"try `gleam run -m birdie`";else if(z instanceof D)return"try accepting with `a`";else if(z instanceof P)return"try `gleam test` again now...";else return"the demo is over!"}function I(z){if(z instanceof b)return"gleam test";else if(z instanceof k)return"gleam run -m birdie";else if(z instanceof U)return"a";else if(z instanceof h)return"r";else return z.value}function Fq(z){let N=t(e(z.steps),(J)=>{if(J instanceof y){let x=J[0];return Y(q([V("with-icon")]),q([Z(q([V("icon hljs-comment")]),q([Q(">")])),Z(q([V("hljs-comment")]),q([Q(I(x))]))]))}else if(J instanceof S)return J[0];else return Y(q([]),q([Q(" ")]))});return Hq(q([Dq(q([V("stack-s")]),q([Y(q([V("stack-xs")]),N),Y(q([V("with-icon")]),q([Z(q([V("icon"),(()=>{let J=z.state;if(J instanceof K)return V("hljs-comment");else if(J instanceof B)return V("hljs-comment");else if(J instanceof E)return O();else if(J instanceof M)return O();else if(J instanceof D)return O();else if(J instanceof P)return O();else return V("hljs-comment")})()]),q([Q(">")])),Kq(q([Xq((()=>{let J=z.state;if(J instanceof K)return!0;else if(J instanceof B)return!0;else if(J instanceof E)return!1;else if(J instanceof M)return!1;else if(J instanceof D)return!1;else if(J instanceof P)return!1;else return!0})()),Zq("text"),Qq(!1),Jq("off"),Vq("off"),xq(z.command),Yq(Wq(z.state)),Nq("terminal-prompt-field"),Eq((J)=>{return new p(J)}),fq((J)=>{return new g(J)})]))]))])),Iq(q([]),`#terminal-prompt-field {
        background-color: transparent;
        font-size: inherit;
        width: 100%;
      }

      #terminal-prompt-field:focus {
        outline: none;
      }
    `)]))}function n(z){return R((N,J)=>{return Uq(z)})}function m(z){return R((N,J)=>{return kq(z)})}function yq(z){return T((N)=>{let J=w(4)+3;return u(J*100,()=>{return N(new l(J,z))})})}function wq(z,N){let J=z.state;if(J instanceof K)return[J,j()];else if(J instanceof B)return[J,j()];else if(J instanceof E)if(N instanceof b)return[new K,Z(q([]),q([Z(q([V("hljs-operator")]),q([Q(" Compiling")])),Q(" example_test")]))];else if(N instanceof k)return[J,F(q([]),q([Q(`\uD83D\uDC26‍⬛ No new snapshots to review
`),Z(q([V("hljs-shell-info")]),q([Q("Hint")])),Q(": "),Z(q([V("hljs-shell-warning")]),q([Q("did you forget to run `gleam test`?")]))]))];else if(N instanceof U)return[J,Y(q([]),q([Q("unknown command: "+I(N))]))];else if(N instanceof h)return[J,Y(q([]),q([Q("unknown command: "+I(N))]))];else return[J,Y(q([]),q([Q("unknown command: "+I(N))]))];else if(J instanceof M)if(N instanceof b)return[new K,Z(q([]),q([Z(q([V("hljs-operator")]),q([Q(" Compiling")])),Q(" example_test")]))];else if(N instanceof k)return[new D,L("","code",q([]),`Reviewing <span class='hljs-shell-warning'>1st</span> out of <span class='hljs-shell-warning'>1</span>

── new snapshot ────────────────────────────────────────────
  <span class='hljs-shell-info'>title</span>: testing the help text
  <span class='hljs-shell-info'>file</span>: ./test/cli.gleam
────────┬───────────────────────────────────────────────────
      <span class='hljs-shell-new'>1 + usage: lucysay [-m message] [-f file]
      2 +
      3 +  -m, --message  the message to be printed
      4 +  -f, --file     a file to read the message from
      5 +  -h, --help     show this help text</span>
────────┴───────────────────────────────────────────────────

  <span class='hljs-shell-new'>a</span> accept     accept the new snapshot
  <span class='hljs-shell-error'>r</span> reject     reject the new snapshot`)];else if(N instanceof U)return[J,Y(q([]),q([Q("unknown command: "+I(N))]))];else if(N instanceof h)return[J,Y(q([]),q([Q("unknown command: "+I(N))]))];else return[J,Y(q([]),q([Q("unknown command: "+I(N))]))];else if(J instanceof D)if(N instanceof b)return[new D,Y(q([]),q([Q("the options are [a]ccept or [r]eject")]))];else if(N instanceof k)return[new D,Y(q([]),q([Q("the options are [a]ccept or [r]eject")]))];else if(N instanceof U)return[new P,Y(q([]),q([Q("\uD83D\uDC26‍⬛ "),Z(q([V("hljs-shell-new")]),q([Q("Accepted one snapshot")]))]))];else if(N instanceof h)return[new E,Y(q([]),q([Q("\uD83D\uDC26‍⬛ "),Z(q([V("hljs-shell-error")]),q([Q("Rejected one snapshot")]))]))];else return[new D,Y(q([]),q([Q("the options are [a]ccept or [r]eject")]))];else if(J instanceof P)if(N instanceof b)return[new K,j()];else if(N instanceof k)return[J,F(q([]),q([Q(`\uD83D\uDC26‍⬛ No new snapshots to review
`),Z(q([V("hljs-shell-info")]),q([Q("Hint")])),Q(": "),Z(q([V("hljs-shell-warning")]),q([Q("did you forget to run `gleam test`?")]))]))];else if(N instanceof U)return[J,Y(q([]),q([Q("unknown command: "+I(N))]))];else if(N instanceof h)return[J,Y(q([]),q([Q("unknown command: "+I(N))]))];else return[J,Y(q([]),q([Q("unknown command: "+I(N))]))];else return[new r,j()]}function Cq(z){let N=qq(z);if(N==="gleam test")return new b;else if(N==="gleam run -m birdie")return new k;else if(N==="a")return new U;else if(N==="r")return new h;else return new Bq(N)}function $q(z){return L("","code",q([]),`<span class='hljs-shell-error'>panic</span> test/example_test.gleam:9
<span class='hljs-shell-info'>test</span>: example_test.usage_text_test
<span class='hljs-shell-info'>info</span>: Birdie snapshot test failed

── new snapshot ────────────────────────────────────────────
<span class='hljs-shell-info'>title</span>: testing the help text
<span class='hljs-shell-info'>hint</span>: <span class='hljs-shell-warning'>run \`gleam run -m birdie\` to review the snapshots</span>
────────┬───────────────────────────────────────────────────
  <span class='hljs-shell-new'>1 + usage: lucysay [-m message] [-f file]
  2 +
  3 +  -m, --message  the message to be printed
  4 +  -f, --file     a file to read the message from
  5 +  -h, --help     show this help text</span>
────────┴───────────────────────────────────────────────────

Finished in 0.0`+v(z)+` seconds
<span class='hljs-shell-error'>1 tests, 1 failures</span>`)}function _q(z){return T((N)=>{let J=w(5)+1;return u(J*10,()=>{return N(new hq(J,z))})})}function vq(z,N){if(N instanceof g){let J=N.command;return[new f(z.state,zq(J),z.steps,z.tests_timing),G()]}else if(N instanceof p)if(N[0]==="Enter"){let x=z.state,A=Cq(z.command),c=wq(z,A),Pq=c[0],d=c[1],C,a=z.steps;if(a instanceof i)C=q([new S(d),new y(A)]);else{let Gq=a;C=H(new S(d),H(new y(A),H(new W,Gq)))}let Oq=new f(Pq,"",C,z.tests_timing),$;if(A instanceof b)$=yq((()=>{if(x instanceof K)return!1;else if(x instanceof B)return!1;else if(x instanceof E)return!1;else if(x instanceof M)return!1;else if(x instanceof D)return!1;else if(x instanceof P)return!0;else return!1})());else $=G();let jq=$;return[Oq,_(q([m("terminal-prompt-field"),n("terminal-prompt-field"),jq]))]}else return[z,G()];else if(N instanceof l){let{elapsed:J,success:x}=N;return[new f(new B,z.command,H(new S(Z(q([]),q([Z(q([V("hljs-operator")]),q([Q("   Running")])),Q(" example_test.main")]))),H(new S(Z(q([]),q([Z(q([V("hljs-operator")]),q([Q("  Compiled")])),Q(" in "),Q("0."+v(J)+"s")]))),z.steps)),z.tests_timing),_q(x)]}else{let{elapsed:J,success:x}=N;return[(()=>{if(x)return new f(new r,z.command,H(new S(F(q([]),q([Z(q([V("hljs-shell-new")]),q([Q(`.
1 passed, no failures`)]))]))),H(new W,z.steps)),z.tests_timing);else return new f(new M,z.command,H(new S($q(J)),H(new W,z.steps)),z.tests_timing)})(),_(q([m("terminal-prompt-field"),n("terminal-prompt-field")]))]}}function Tq(z){return[new f(new E,"",q([]),z),G()]}function Mq(){let z=Sq(Tq,vq,Fq),N=bq(z,"#terminal",w(5)+1);if(!(N instanceof o))throw s("let_assert",Aq,"blog/interactive/birdie_terminal",48,"main","Pattern match failed, no pattern matched the value.",{value:N,start:838,end:922,pattern_start:849,pattern_end:854});return}Mq();
