import{$ as Kq,B as Nq,C as V,D as O,E as Qq,F as Vq,H as Xq,I as Yq,L as Zq,N as xq,O as Hq,P as G,Q as R,R as L,S as v,V as j,W as Iq,X as u,Y as Q,Z as Dq,_ as Y,a as X,aa as F,b as H,ba as Z,c as q,ca as Sq,d as o,da as bq,e as s,ea as Eq,g as e,ha as fq,ia as kq,j as t,ja as Uq,k as qq,ka as hq,la as r,o as zq,s as T,t as Jq,x as w}from"./birdie_terminal-07np7pjt.js";var Aq="src/blog/interactive/birdie_terminal.gleam";class f extends X{constructor(z,N,J,x){super();this.state=z,this.command=N,this.steps=J,this.tests_timing=x}}class y extends X{constructor(z){super();this[0]=z}}class S extends X{constructor(z){super();this[0]=z}}class W extends X{}class K extends X{}class B extends X{}class E extends X{}class M extends X{}class D extends X{}class P extends X{}class g extends X{}class p extends X{constructor(z){super();this.command=z}}class l extends X{constructor(z){super();this[0]=z}}class c extends X{constructor(z,N){super();this.elapsed=z,this.success=N}}class Bq extends X{constructor(z,N){super();this.elapsed=z,this.success=N}}class b extends X{}class k extends X{}class U extends X{}class h extends X{}class Mq extends X{constructor(z){super();this.value=z}}function Wq(z){return[new f(new E,"",q([]),z),G()]}function Fq(z){return R((N)=>{let J=w(4)+3;return r(J*100,()=>{return N(new c(J,z))})})}function yq(z){return R((N)=>{let J=w(5)+1;return r(J*10,()=>{return N(new Bq(J,z))})})}function m(z){return L((N,J)=>{return hq(z)})}function i(z){return L((N,J)=>{return Uq(z)})}function wq(z){return u("","code",q([]),`<span class='hljs-shell-error'>panic</span> test/example_test.gleam:9
<span class='hljs-shell-info'>test</span>: example_test.usage_text_test
<span class='hljs-shell-info'>info</span>: Birdie snapshot test failed

── new snapshot ────────────────────────────────────────────
<span class='hljs-shell-info'>title</span>: testing the help text
<span class='hljs-shell-info'>hint</span>: <span class='hljs-shell-warning'>run \`gleam run -m birdie\` to review the snapshots</span>
────────┬───────────────────────────────────────────────────
  <span class='hljs-shell-new'>1 + usage: lucysay [-m message] [-f file]
  2 +
  3 +  -m, --message  the message to be printed
  4 +  -f, --file     a file to read the message from
  5 +  -h, --help     show this help text</span>
────────┴───────────────────────────────────────────────────

Finished in 0.0`+T(z)+` seconds
<span class='hljs-shell-error'>1 tests, 1 failures</span>`)}function I(z){if(z instanceof b)return"gleam test";else if(z instanceof k)return"gleam run -m birdie";else if(z instanceof U)return"a";else if(z instanceof h)return"r";else return z.value}function Cq(z,N){let J;if(J=z.state,J instanceof K)return[J,j()];else if(J instanceof B)return[J,j()];else if(J instanceof E)if(N instanceof b)return[new K,Z(q([]),q([Z(q([V("hljs-operator")]),q([Q(" Compiling")])),Q(" example_test")]))];else if(N instanceof k)return[J,F(q([]),q([Q(`\uD83D\uDC26‍⬛ No new snapshots to review
`),Z(q([V("hljs-shell-info")]),q([Q("Hint")])),Q(": "),Z(q([V("hljs-shell-warning")]),q([Q("did you forget to run `gleam test`?")]))]))];else if(N instanceof U)return[J,Y(q([]),q([Q("unknown command: "+I(N))]))];else if(N instanceof h)return[J,Y(q([]),q([Q("unknown command: "+I(N))]))];else return[J,Y(q([]),q([Q("unknown command: "+I(N))]))];else if(J instanceof M)if(N instanceof b)return[new K,Z(q([]),q([Z(q([V("hljs-operator")]),q([Q(" Compiling")])),Q(" example_test")]))];else if(N instanceof k)return[new D,u("","code",q([]),`Reviewing <span class='hljs-shell-warning'>1st</span> out of <span class='hljs-shell-warning'>1</span>

── new snapshot ────────────────────────────────────────────
  <span class='hljs-shell-info'>title</span>: testing the help text
  <span class='hljs-shell-info'>file</span>: ./test/cli.gleam
────────┬───────────────────────────────────────────────────
      <span class='hljs-shell-new'>1 + usage: lucysay [-m message] [-f file]
      2 +
      3 +  -m, --message  the message to be printed
      4 +  -f, --file     a file to read the message from
      5 +  -h, --help     show this help text</span>
────────┴───────────────────────────────────────────────────

  <span class='hljs-shell-new'>a</span> accept     accept the new snapshot
  <span class='hljs-shell-error'>r</span> reject     reject the new snapshot`)];else if(N instanceof U)return[J,Y(q([]),q([Q("unknown command: "+I(N))]))];else if(N instanceof h)return[J,Y(q([]),q([Q("unknown command: "+I(N))]))];else return[J,Y(q([]),q([Q("unknown command: "+I(N))]))];else if(J instanceof D)if(N instanceof b)return[new D,Y(q([]),q([Q("the options are [a]ccept or [r]eject")]))];else if(N instanceof k)return[new D,Y(q([]),q([Q("the options are [a]ccept or [r]eject")]))];else if(N instanceof U)return[new P,Y(q([]),q([Q("\uD83D\uDC26‍⬛ "),Z(q([V("hljs-shell-new")]),q([Q("Accepted one snapshot")]))]))];else if(N instanceof h)return[new E,Y(q([]),q([Q("\uD83D\uDC26‍⬛ "),Z(q([V("hljs-shell-error")]),q([Q("Rejected one snapshot")]))]))];else return[new D,Y(q([]),q([Q("the options are [a]ccept or [r]eject")]))];else if(J instanceof P)if(N instanceof b)return[new K,j()];else if(N instanceof k)return[J,F(q([]),q([Q(`\uD83D\uDC26‍⬛ No new snapshots to review
`),Z(q([V("hljs-shell-info")]),q([Q("Hint")])),Q(": "),Z(q([V("hljs-shell-warning")]),q([Q("did you forget to run `gleam test`?")]))]))];else if(N instanceof U)return[J,Y(q([]),q([Q("unknown command: "+I(N))]))];else if(N instanceof h)return[J,Y(q([]),q([Q("unknown command: "+I(N))]))];else return[J,Y(q([]),q([Q("unknown command: "+I(N))]))];else return[new g,j()]}function $q(z){let N=zq(z);if(N==="gleam test")return new b;else if(N==="gleam run -m birdie")return new k;else if(N==="a")return new U;else if(N==="r")return new h;else return new Mq(N)}function _q(z,N){if(N instanceof p){let J=N.command;return[new f(z.state,Jq(J),z.steps,z.tests_timing),G()]}else if(N instanceof l)if(N[0]==="Enter"){let x=z.state,A=$q(z.command),d=Cq(z,A),a,C;a=d[0],C=d[1];let $,n=z.steps;if(n instanceof o)$=q([new S(C),new y(A)]);else{let Gq=n;$=H(new S(C),H(new y(A),H(new W,Gq)))}let Oq=new f(a,"",$,z.tests_timing),_;if(A instanceof b)_=Fq((()=>{if(x instanceof K)return!1;else if(x instanceof B)return!1;else if(x instanceof E)return!1;else if(x instanceof M)return!1;else if(x instanceof D)return!1;else if(x instanceof P)return!0;else return!1})());else _=G();let jq=_;return[Oq,v(q([i("terminal-prompt-field"),m("terminal-prompt-field"),jq]))]}else return[z,G()];else if(N instanceof c){let{elapsed:J,success:x}=N;return[new f(new B,z.command,H(new S(Z(q([]),q([Z(q([V("hljs-operator")]),q([Q("   Running")])),Q(" example_test.main")]))),H(new S(Z(q([]),q([Z(q([V("hljs-operator")]),q([Q("  Compiled")])),Q(" in "),Q("0."+T(J)+"s")]))),z.steps)),z.tests_timing),yq(x)]}else{let{elapsed:J,success:x}=N;return[(()=>{if(x)return new f(new g,z.command,H(new S(F(q([]),q([Z(q([V("hljs-shell-new")]),q([Q(`.
1 passed, no failures`)]))]))),H(new W,z.steps)),z.tests_timing);else return new f(new M,z.command,H(new S(wq(J)),H(new W,z.steps)),z.tests_timing)})(),v(q([i("terminal-prompt-field"),m("terminal-prompt-field")]))]}}function vq(z){if(z instanceof K)return"compiling...";else if(z instanceof B)return"running tests...";else if(z instanceof E)return"try `gleam test`...";else if(z instanceof M)return"try `gleam run -m birdie`";else if(z instanceof D)return"try accepting with `a`";else if(z instanceof P)return"try `gleam test` again now...";else return"the demo is over!"}function Tq(z){let N=qq(t(z.steps),(J)=>{if(J instanceof y){let x=J[0];return Y(q([V("with-icon")]),q([Z(q([V("icon hljs-comment")]),q([Q(">")])),Z(q([V("hljs-comment")]),q([Q(I(x))]))]))}else if(J instanceof S)return J[0];else return Y(q([]),q([Q(" ")]))});return Iq(q([Kq(q([V("stack-s")]),q([Y(q([V("stack-xs")]),N),Y(q([V("with-icon")]),q([Z(q([V("icon"),(()=>{let J=z.state;if(J instanceof K)return V("hljs-comment");else if(J instanceof B)return V("hljs-comment");else if(J instanceof E)return O();else if(J instanceof M)return O();else if(J instanceof D)return O();else if(J instanceof P)return O();else return V("hljs-comment")})()]),q([Q(">")])),Sq(q([Yq((()=>{let J=z.state;if(J instanceof K)return!0;else if(J instanceof B)return!0;else if(J instanceof E)return!1;else if(J instanceof M)return!1;else if(J instanceof D)return!1;else if(J instanceof P)return!1;else return!0})()),xq("text"),Vq(!1),Nq("off"),Xq("off"),Hq(z.command),Zq(vq(z.state)),Qq("terminal-prompt-field"),fq((J)=>{return new l(J)}),kq((J)=>{return new p(J)})]))]))])),Dq(q([]),`#terminal-prompt-field {
        background-color: transparent;
        font-size: inherit;
        width: 100%;
      }

      #terminal-prompt-field:focus {
        outline: none;
      }
    `)]))}function Pq(){let z=bq(Wq,_q,Tq),N=Eq(z,"#terminal",w(5)+1);if(!(N instanceof s))throw e("let_assert",Aq,"blog/interactive/birdie_terminal",48,"main","Pattern match failed, no pattern matched the value.",{value:N,start:838,end:922,pattern_start:849,pattern_end:854});return}Pq();
